TEXT_PLAY = "SPILA"; //PLAY
TEXT_SCORE = "STIG";//SCORE
TEXT_GAME_OVER = "LEIK LOKIÐ"; //GAME OVER
TEXT_NEXT = "NÆST"; //NEXT
TEXT_HELP = "NOTAÐU ÖRVATAKKANA TIL AÐ RAÐA SAMAN ÞREMUR EÐA FLEIRI"; //MATCH 3 OR MORE SIMILAR ELEMENTS, USING ARROW KEYS OR BUTTONS