var CANVAS_WIDTH = 768;
var CANVAS_HEIGHT = 1024;

var FPS_TIME      = 1000/24;
var DISABLE_SOUND_MOBILE = true;

var STATE_LOADING = 0;
var STATE_MENU    = 1;
var STATE_HELP    = 1;
var STATE_GAME    = 3;

var ON_MOUSE_DOWN = 0;
var ON_MOUSE_UP   = 1;
var ON_MOUSE_OVER = 2;
var ON_MOUSE_OUT  = 3;
var ON_DRAG_START = 4;
var ON_DRAG_END   = 5;

var NUM_LEVELS;
var BOARD_OFFSET_X;
var BOARD_OFFSET_Y;
var BOARD_ROWS = 16; 
var BOARD_COLS = 12; 
var BALL_SPEED;
var NUM_BALL_COLORS;
var MAX_BALL_ADJACENCY = 40;
var TIME_FOR_UPDATING_PHYSICS = 8;
var NUM_LAUNCH_FOR_EARTHQUAKE;
var EARTHQUAKE_TIME = 200;
var OFFSET_Y_GAME_OVER;

var SCORE_EXPLOSION_BALL; 
var SCORE_FALLEN_BALL;

var CODE_EXPLODING_BALL = 11;
var CODE_EXPLODING_ISLE = 44;
var CODE_EXPLODING_BOMB = 66;
var CODE_BOMB_BALL = 11;
var CODE_RAINBOW_BALL = 12;
