TEXT_GAMEOVER  = "ÞÚ KLÁRAÐIR ";
TEXT_SUDOKU    = " SUDOKU";
TEXT_IN        = " Í ";
TEXT_HELP_USED = "ÞÚ NOTAÐIR EFTIRFARANDI HJÁLPARTÓL:";
TEXT_HELPS_USED= "ÞÚ NOTAÐIR HJÁLP:";
TEXT_HELP_NOTE = "FYLLI MEÐ TILLÖGUM";
TEXT_HELP_SOLVE= "LAUSN";
TEXT_HELP_TIME = "SLEPPA TÍMA";
TEXT_HELP_HINT = " VÍSBENDING";
TEXT_HELP_HINTS = " VÍSBENDINGAR";
TEXT_SCORE     = "STIG";
TEXT_PLAY      = "SPILA";
TEXT_RESTART   = "BYRJA AFTUR";
TEXT_TIME      = "TÍMI";
TEXT_GENERATE_SUDOKU = "SET UPP SUDOKU. VINSAMLEGAST BÍÐIÐ.";

TEXT_TOP_MODE  = "STYRKLEIKAFLOKKAR";
TEXT_EASY      = "LÉTT";
TEXT_MEDIUM    = "MIÐLUNGS";
TEXT_HARD      = "ERFIT";

TEXT_HELP0     = "REGLUR";
TEXT_HELP1     = "FYLLTU Í EYÐURNAR MEÐ TÖLUM FRÁ 1 UPP Í 9.  HVER RÖÐ, DÁLKUR EÐA 3X3 KASSI VERÐUR AÐ INNIHALDA TÖLURNAR 1 TIL 9 AÐEINS EINU SINNI.";

TEXT_HELP0_PAGE2 = "HVERNIG";
//TEXT_HELP1_PAGE2 = "USE KEYBOARD OR NUMBER BUTTONS TO FILL IN THE BLANKS. THERE ARE 3 DIFFERENT GAME MODES:";
TEXT_HELP1_PAGE2 = "NOTAÐU LYKLABORÐIÐ EÐA TALNABORÐIÐ TIL AÐ FYLLA INN Í EYÐURNAR.  ÞAÐ ERU ÞRÍR STYRKLEIKAFLOKKAR:";
//TEXT_HELP1_MOB_PAGE2 = "USE NUMBER BUTTONS TO FILL BLANKS IN GAME. THERE ARE 3 DIFFERENT GAME MODES:";
TEXT_HELP1_MOB_PAGE2 = "NOTAÐU TALNABORÐIÐ TIL AÐ FYLLA INN Í EYÐURNAR Í LEIKNUM. ÞAÐ ERU ÞRÍR STYRKLEIKAFLOKKAR";

//TEXT_HELP2_PAGE2 = '"CELL FIRST" MODE: CLICK FIRST THE CELL YOU WANT TO FILL IN, THEN SELECT THE NUMBER YOU WANT TO ENTER';
TEXT_HELP2_PAGE2 = '„KASSI FYRST“: ÞÚ VELUR FYRST KASSA OG SVO TÖLU TIL AÐ SETJA Í KASSANN.';
//TEXT_HELP3_PAGE2 = '"NUMBER FIRST" MODE: SELECT THE NUMBER YOU WANT TO ENTER FIRST, THEN CLICK THE CELL YOU WANT TO FILL IN';
TEXT_HELP3_PAGE2 = '„TALA FYRST“: ÞÚ VELUR FYRST TÖLU OG SVO KASSANN TIL AÐ SETJA TÖLUNA Í.';
//TEXT_HELP4_PAGE2 = 'MEMO MODE: THIS BUTTON ALLOWS YOU TO WRITE DOWN A MEMO IN A BLANK';
TEXT_HELP4_PAGE2 = '„MINNISPUNKTUR“: HÉR GETUR ÞÚ SETT INN TILLÖGUR AÐ TÖLU Í KASSA ÁN ÞESS AÐ FESTA HANA.';

//TEXT_FILL_WITH_NOTE = "FILL THE BOARD WITH NOTES";
TEXT_FILL_WITH_NOTE = "BIRTA TILLÖGUR";
//TEXT_DELETE_ALL_NOTE = "DELETE ALL NOTES";
TEXT_DELETE_ALL_NOTE = "AFBIRTA TILLÖGUR";
TEXT_SOLVE = "LEYSA SUDOKU ÞRAUT";
TEXT_RESET = "ENDURSTILLA SUDOKU";
TEXT_SETNOTIME = "SPILA ÁN TÍMATÖKU";
TEXT_GETHINT = "FÁ VÍSBENDINGU";
