TEXT_GAMEOVER  = "YOU COMPLETED ";
TEXT_SUDOKU    = " SUDOKU";
TEXT_IN        = " IN ";
TEXT_HELP_USED = "YOU USED FOLLOWING HELP:";
TEXT_HELPS_USED= "YOU USED FOLLOWING HELPS:";
TEXT_HELP_NOTE = "NOTES AUTOFILL";
TEXT_HELP_SOLVE= "SOLVER";
TEXT_HELP_TIME = "SET NO TIME";
TEXT_HELP_HINT = " HINT";
TEXT_HELP_HINTS = " HINTS";
TEXT_SCORE     = "SCORE";
TEXT_PLAY      = "PLAY";
TEXT_RESTART   = "RESTART";
TEXT_TIME      = "TIME";
TEXT_GENERATE_SUDOKU = "GENERATING SUDOKU. PLEASE WAIT";

TEXT_TOP_MODE  = "SELECT YOUR LEVEL";
TEXT_EASY      = "BEGINNER";
TEXT_MEDIUM    = "INTERMEDIATE";
TEXT_HARD      = "ADVANCED";

TEXT_HELP0     = "RULES";
TEXT_HELP1     = "FILL IN THE BLANKS WITH NUMBERS FROM 1 TO 9. EACH ROW, COLUMN OR 3X3 BLOCK, MUST CONTAIN THE NUMBER 1 THROUGH 9 EXACTLY ONCE";

TEXT_HELP0_PAGE2 = "HOW-TO";
TEXT_HELP1_PAGE2 = "USE KEYBOARD OR NUMBER BUTTONS TO FILL IN THE BLANKS. THERE ARE 3 DIFFERENT GAME MODES:";
TEXT_HELP1_MOB_PAGE2 = "USE NUMBER BUTTONS TO FILL BLANKS IN GAME. THERE ARE 3 DIFFERENT GAME MODES:";

TEXT_HELP2_PAGE2 = '"CELL FIRST" MODE: CLICK FIRST THE CELL YOU WANT TO FILL IN, THEN SELECT THE NUMBER YOU WANT TO ENTER';
TEXT_HELP3_PAGE2 = '"NUMBER FIRST" MODE: SELECT THE NUMBER YOU WANT TO ENTER FIRST, THEN CLICK THE CELL YOU WANT TO FILL IN';
TEXT_HELP4_PAGE2 = 'MEMO MODE: THIS BUTTON ALLOWS YOU TO WRITE DOWN A MEMO IN A BLANK';

TEXT_FILL_WITH_NOTE = "FILL THE BOARD WITH NOTES";
TEXT_DELETE_ALL_NOTE = "DELETE ALL NOTES";
TEXT_SOLVE = "SOLVE THE SUDOKU";
TEXT_RESET = "RESET THE SUDOKU";
TEXT_SETNOTIME = "PLAY WITHOUT TIME";
TEXT_GETHINT = "GET A HINT";
